global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "kafka"
    static_configs:
      - targets: ['kafka_exporter:9308']
  
  - job_name: "producer"
    static_configs:
      - targets: ['producer:4000']

  - job_name: "consumer"
    static_configs:
      - targets: ['consumer:5000']
